version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./container/db/Dockerfile
    ports:
      - 5050:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: librarynet
    volumes:
      - ./database:/usr/src
      - librarynet_db_data:/var/lib/postgresql/data
      # - ./container/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    container_name: librarynet_db
volumes:
  librarynet_db_data: {}
  # server:
  #   build:
  #     context: .
  #     dockerfile: ./container/server/Dockerfile
  #   depends_on:
  #     - db
  #   tty: true
  #   ports:
  #     - 8888:8888
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres@librarynet_db:5432/librarynet
  #   container_name: node_server
  #   command: yarn devtsd
  #   volumes:
  #     - ./server:/usr/src/app
