version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./container/db/Dockerfile
    ports:
      - 5050:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: librarynet
    volumes:
      - ./database:/usr/src
      - librarynet_db_data:/var/lib/postgresql/data
      # - ./container/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    container_name: librarynet_db
  redis:
    image: redis
    ports:
      - 6060:6379
    container_name: librarynet_redis
  server:
    build:
      context: .
      dockerfile: ./container/server/Dockerfile
    depends_on:
      - db
      - redis
    tty: true
    ports:
      - 4000:4000
    command: yarn dev-ts
    volumes:
      - ./server:/usr/src/app
      # https://medium.com/@semur.nabiev/how-to-make-docker-compose-volumes-ignore-the-node-modules-directory-99f9ec224561
      - /usr/src/app/node_modules
    container_name: librarynet_server
  web:
    build:
      context: .
      dockerfile: ./container/web/Dockerfile
    depends_on:
      - db
      - redis
      - server
    tty: true
    ports:
      - 3000:3000
    command: yarn dev
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    container_name: librarynet_web
volumes:
  librarynet_db_data: {}

