version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./container/db/Dockerfile
    ports:
      - 5050:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: librarynet
    volumes:
      - ./database:/usr/src
      - librarynet_db_data:/var/lib/postgresql/data
      # - ./container/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    container_name: librarynet_db
  server:
    build:
      context: .
      dockerfile: ./container/server/Dockerfile
    depends_on:
      - db
    tty: true
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@librarynet_db:5432/librarynet
    # command: yarn dev-tsd
    volumes:
      - ./server:/usr/src/app
      # 初回起動時にホスト側のnode-modulesを消しておくとうまくいくため
      # ボリュームを使ったnode-modulesのマウントはしない
      # - .server/node-modules:/usr/src/app/node-modules
    container_name: node_server
volumes:
  librarynet_db_data: {}

